[package]
name = "compression"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.93"
web-sys = { version = "0.3.70", features = [] }
huffman_derive = { path = "../huffman_derive" }
huffman = { path = "../huffman" }
world = { path = "../world" }
