[package]
name = "world"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.202", features = ["derive"] }
rand = "0.9.0-alpha.1"

[dependencies.getrandom]
version = "0.2.15"
features = ["js"]

[lib]
name = "world"
path = "lib.rs"
