[package]
name = "sweeper-server"
edition = "2021"

[dependencies]
rand = "0.8.5"
derive_more = "0.99.17"
futures-util = "0.3.30"
tokio = { version = "1.37.0", features = ["rt", "rt-multi-thread", "macros", "time"] }
rust_socketio = { version = "*", features = ["async"] }
axum = "0.7.5"
tower-http = { version = "0.5.2", features = ["fs"] }
tower-sessions = "0.12.2"
socketioxide = "0.13.1"
serde = { version = "1.0.202", features = ["derive"] }
serde_json = "1.0.117"
postcard = { version = "1.0.8", features = ["alloc"] }
world = { path = "../world" }
clap = { version = "4.5.17", features = ["derive"] }
include_dir = "0.7.4"
mime_guess = "2.0.4"