name: Rust

on:
  push:
    tags:
      - "*"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    permissions: write-all

    steps:
    - uses: actions/checkout@v4
    - run: rustup toolchain install stable --profile minimal --no-self-update
    - uses: Swatinem/rust-cache@v2
      with:
        cache-all-crates: 'true'
        cache-on-failure: 'true'
    - name: Install wasm-pack
      run: cargo install wasm-pack
    - name: Build WASM
      run: wasm-pack build "crates/wgpu-frontend" --out-dir "../../crates/server/static" --release --target=web --no-typescript --no-pack
    - name: Build
      run: cargo build --bin sweeper-server
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
    - name: upload linux artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./target/release/sweeper-server
        asset_name: sweeper-server
        asset_content_type: 'application/binary'
